jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true
application:
  name: client-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 1000