server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          application: client-service
          default-label: master
          uri: https://github.com/LauraGullo/Gullo-PatagoniaTest.git
          search-paths: config-data

  application:
    name: config-service
